import type { TeamContent } from "../types/globals";

export const teamContent: TeamContent = {
  title: "Our Squads",
  subtitle:
    "The elite athletes representing the standard of Guyanese volleyball across all levels of competition.",
  teams: [
    {
      teamName: "Senior Male Team",
      description:
        "The vanguard of our club, the senior male team's is built on power, precision, and relentless defense. Competing at the highest levels of the Demerara Volleyball Association, they embody the 'One Shot One Kill' philosophy on the court.",
      division: "Division B",
      accolades: [
        "Glasgow Rangers Volleyball Club Invitational Runners-Up 2026",
      ],
      url: "/teams/senior-male",
      teamPhoto: {
        url: "../assets/images/senior-male-team-photo.webp",
        alternativeText: "Senior Male Team Photo",
      },
      players: [
        // Tayshaun Griffith
        {
          name: "Tayshaun Griffith",
          position: "Outside Hitter",
          jerseyNumber: 5,
          shirtSize: "M",
          waistSize: 33,
          shoeSize: { US: 11, EU: 45, UK: 10.5 }, // Standard conversions used for EU/UK
          gender: "Male",
          height: "6'0\"",
          standingReach: "7'10\"",
          verticalJump: '32"',
          tagline: "The Silent Assassin",
          accolades: [
            "Glasgow Rangers Volleyball Club Invitational All-Star 2026",
          ],
          isCaptain: true,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/tayshaun-griffith.webp",
            alternativeText: "Tayshaun Griffith Player Profile Photo",
          },
        },
        // Anphany Fredericks
        {
          name: "Anphany Fredericks",
          position: "Middle Blocker",
          jerseyNumber: 2,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 11, EU: 45, UK: 10.5 }, // Normalized "10 1/2 or 11" to 11
          gender: "Male",
          height: "6'0\"",
          standingReach: "7'9\"",
          verticalJump: '34"',
          tagline: "The Silent Wall",
          accolades: [
            "Glasgow Rangers Volleyball Club Invitational Best Blocker 2026",
          ],
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/anphany-fredericks.webp",
            alternativeText: "Anphany Fredericks Player Profile Photo",
          },
        },
        // Ezekiel Thomas
        {
          name: "Ezekiel Thomas",
          position: "Setter",
          jerseyNumber: 1,
          shirtSize: "L",
          waistSize: 32,
          shoeSize: { US: 10.5, EU: 44, UK: 10 },
          gender: "Male",
          height: "5'11\"",
          standingReach: "7'10\"",
          verticalJump: '32"',
          tagline: "The Floor General",
          accolades: [
            "Glasgow Rangers Volleyball Club Invitational All-Star 2026",
          ],
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Shervinton Fraser
        {
          name: "Shervinton Fraser",
          position: "Middle Blocker",
          jerseyNumber: null,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 9.5, EU: 43, UK: 9 },
          gender: "Male",
          height: "6'1\"",
          standingReach: "7'11\"",
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Garfield George Williams
        {
          name: "Garfield George Williams",
          position: "Opposite Hitter",
          jerseyNumber: 7,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Oscar Adams
        {
          name: "Oscar Adams",
          position: "Outside Hitter",
          jerseyNumber: 3,
          shirtSize: "L",
          waistSize: 38,
          shoeSize: { US: 10.5, EU: 44, UK: 10 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Sa-Yoor Headley
        {
          name: "Sa-Yoor Headley",
          tagline: "The Energizer",
          position: "Middle Blocker",
          jerseyNumber: 15,
          shirtSize: "M",
          waistSize: 34,
          shoeSize: { US: 10, EU: 43, UK: 9.5 },
          gender: "Male",
          height: "5'11\"",
          standingReach: "7'9.75\"",
          verticalJump: '30"',
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Erlawn Sullivan
        {
          name: "Erlawn Sullivan",
          position: "Setter",
          jerseyNumber: 4,
          shirtSize: "S",
          waistSize: 30, // Parsed "30*31" down to 30
          shoeSize: { US: 9, EU: 42, UK: 8.5 },
          gender: "Male",
          height: "6'0\"",
          standingReach: "7'10\"",
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // John Abrams
        {
          name: "John Abrams",
          position: "Setter",
          jerseyNumber: 8,
          shirtSize: "L",
          waistSize: 36,
          shoeSize: { US: 11, EU: 45, UK: 10.5 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Akwain Bowen
        {
          name: "Akwain Bowen",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: "M",
          waistSize: null,
          shoeSize: { US: 11, EU: 45, UK: 10.5 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Kobe Marshall
        {
          name: "Kobe Marshall",
          position: "Middle Blocker",
          jerseyNumber: 19,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: "6'0.5\"",
          standingReach: "7'11\"",
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Ammiel Michael
        {
          name: "Ammiel Michael",
          position: "Setter",
          jerseyNumber: 23,
          shirtSize: "M",
          waistSize: null, // Left out in raw text
          shoeSize: { US: 11, EU: 45, UK: 10.5 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/ammiel-michael.webp",
            alternativeText: "Ammiel Michael Player Profile Photo",
          },
        },
        // Shemar Heywood
        {
          name: "Shemar Heywood",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 10.5, EU: 44, UK: 10 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/shemar-heywood.webp",
            alternativeText: "Shemar Heywood Player Profile Photo",
          },
        },
        // Jomel Robertson
        {
          name: "Jomel Robertson",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 10.5, EU: 44, UK: 10 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        // Immanuel LaRose
        {
          name: "Immanuel LaRose",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        // Eli Bowen
        {
          name: "Eli Bowen",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        // Rohan Donaldson Jr.
        {
          name: "Rohan Donaldson Jr.",
          position: "Outside Hitter",
          jerseyNumber: 16,
          shirtSize: "L",
          waistSize: 44,
          shoeSize: { US: 9.5, EU: 43, UK: 9 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        // Lennox McCalman
        {
          name: "Lennox McCalman",
          position: "Setter",
          jerseyNumber: 9,
          shirtSize: "XL",
          waistSize: 40,
          shoeSize: { US: 9, EU: 42, UK: 8.5 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        // Adrian
        {
          name: "Adrian",
          position: "Opposite Hitter",
          jerseyNumber: null,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: "5'10.75\"",
          standingReach:"7'11\"",
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
      ],
    },
    {
      teamName: "Senior Female Team",
      description:
        "A force of technical brilliance and tactical discipline. The female's squad consistently dominates local tournaments through exceptional serve-receive and a fast-paced offensive system.",
      division: "Division B",
      accolades: [
        "Glasgow Rangers Volleyball Club Invitational Runners-Up 2026",
      ],
      url: "/teams/senior-female",
      teamPhoto: {
        url: "../assets/images/senior-female-team-photo.webp",
        alternativeText: "Senior Female Team Photo",
      },
      players: [
        {
          name: "Precia Griffith",
          position: "Setter",
          jerseyNumber: 5,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        {
          name: "Alliyah Antigua",
          position: "Middle Blocker",
          jerseyNumber: 10,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/alliyah-antigua.webp",
            alternativeText: "Alliyah Antigua Player Profile Photo",
          },
        },
        {
          name: "Alliyah Blackman",
          position: "Outside Hitter",
          jerseyNumber: 11,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 8.5, EU: 39, UK: 6.5 },
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/alliyah-blackman.webp",
            alternativeText: "Alliyah Blackman Player Profile Photo",
          },
        },
        {
          name: "Sharissa Moore",
          position: "Middle Blocker",
          jerseyNumber: 3,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/sharissa-moore.webp",
            alternativeText: "Sharissa Moore Player Profile Photo",
          },
        },
        {
          name: "Densea Duncan",
          position: "Outside Hitter", // Default fallback if unspecified
          jerseyNumber: 4,
          shirtSize: null,
          waistSize: 27,
          shoeSize: { US: 9.5, EU: 41, UK: 7.5 }, // Interpreted from 40/41 regional shoe sizing
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/densea-duncan.webp",
            alternativeText: "Densea Duncan Player Profile Photo",
          },
        },
        {
          name: "Sabita Mangar",
          position: "Libero",
          jerseyNumber: 2,
          shirtSize: "S",
          waistSize: 28,
          shoeSize: { US: 6.5, EU: 37, UK: 4.5 },
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/sabita-mangar.webp",
            alternativeText: "Sabita Mangar Player Profile Photo",
          },
        },
        {
          name: "Melanie Wallace",
          position: "Outside Hitter",
          jerseyNumber: 14,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        {
          name: "Jania Squires",
          position: "Outside Hitter",
          jerseyNumber: 1,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: null,
        },
        {
          name: "Keisha Primo",
          position: "Middle Blocker",
          jerseyNumber: 6,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/keisha-primo.webp",
            alternativeText: "Keisha Primo Player Profile Photo",
          },
        },
        {
          name: "Serika David",
          position: "Outside Hitter",
          jerseyNumber: 13,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        {
          name: "Jamayfia Smith",
          position: "Setter",
          jerseyNumber: 7,
          shirtSize: "M",
          waistSize: 34,
          shoeSize: { US: 9.5, EU: 41, UK: 7.5 }, // Parsed raw "41" to shoe size object
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/jamayfia-smith.webp",
            alternativeText: "Jamayfia Smith Player Profile Photo",
          },
        },
        {
          name: "Serina Headley",
          position: "Outside Hitter",
          jerseyNumber: 15,
          shirtSize: "M",
          waistSize: 32,
          shoeSize: { US: 7, EU: 37.5, UK: 5 },
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: true,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/serina-headley.webp",
            alternativeText: "Serina Headley Player Profile Photo",
          },
        },
        {
          name: "Danica Wilson",
          position: "Outside Hitter",
          jerseyNumber: 8,
          shirtSize: "M",
          waistSize: null, // "L" in raw string context matches shift to sizing fields
          shoeSize: { US: 9.5, EU: 41, UK: 7.5 },
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/danica-wilson.webp",
            alternativeText: "Danica Wilson Player Profile Photo",
          },
        },
        {
          name: "Dacia Courtman",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: "M",
          waistSize: null,
          shoeSize: { US: 7, EU: 37.5, UK: 5 },
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: false,
          photo: {
            url: "/images/player-profiles/dacia-courtman.webp",
            alternativeText: "Dacia Courtman Player Profile Photo",
          },
        },
        {
          name: "Ronique Perry",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        {
          name: "Ariella Kabelli",
          position: "Outside Hitter",
          jerseyNumber: 9,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
        {
          name: "Xaffyrrahyah Roos",
          position: "Outside Hitter",
          jerseyNumber: 12,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: false,
          isJunior: false,
          photo: null,
        },
      ],
    },
    {
      teamName: "Junior Team",
      description:
        "The future of Glasgow Rangers VC. Our junior program focuses on fundamentals, athletic development, and instilling the competitive mindset required for senior-level success.",
      accolades: null,
      division: null,
      url: "/teams/junior",
      teamPhoto: {
        url: "../assets/images/junior-team-photo.webp",
        alternativeText: "Junior Team Photo",
      },
      players: [
        {
          name: "Sharique Mohamed",
          position: "Setter",
          jerseyNumber: null,
          shirtSize: "M", // "Children's 12" maps generally to Youth Medium
          waistSize: 28, // Extracted numerical value from "Children's 28"
          shoeSize: { US: 5, EU: 37, UK: 4.5 }, // Youth/Kids size 5 Y
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: true, // Set to true based on explicit "Children's" data context
          photo: null,
        },
        {
          name: "Jayden Simpson",
          position: "Outside Hitter",
          jerseyNumber: null,
          shirtSize: "XL", // "Children's XL"
          waistSize: null, // "Children's XL" used for waist slot in raw text; set to null
          shoeSize: { US: 9.5, EU: 43, UK: 9 }, // Handled as standard translation or older youth sizing
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: true,
          photo: null,
        },
        {
          name: "Beres",
          position: "Middle Blocker",
          jerseyNumber: null,
          shirtSize: null,
          waistSize: null,
          shoeSize: null,
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: true,
          photo: null,
        },
        {
          name: "Collis Robertson",
          position: "Middle Blocker",
          jerseyNumber: null,
          shirtSize: "S", // "Children's 12" / youth size context
          waistSize: 16, // Extracted from "Children's 16"
          shoeSize: { US: 8.5, EU: 42, UK: 8 },
          gender: "Male",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: true,
          photo: null,
        },
        {
          name: "Delesha Robertson",
          position: "Outside Hitter", // Default fallback for empty position slot
          jerseyNumber: null,
          shirtSize: "S", // "Children's Small"
          waistSize: 22, // "Children's 22"
          shoeSize: { US: 3.5, EU: 35.5, UK: 3 }, // Parsed regional "Children's 35/36" context
          gender: "Female",
          height: null,
          tagline: undefined,
          accolades: null,
          isCaptain: false,
          isActive: true,
          isJunior: true,
          photo: null,
        },
      ],
    },
  ],
};
